# Travis CI Configuration file
# @link https://travis-ci.org/

# Using Java for the project
language: java
jdk:
  - oraclejdk8
  - oraclejdk9

script:
  # Unit and integration tests are run
  - mvn clean verify

after_success:
    - bash <(curl -s https://codecov.io/bash)

